coursify/config/routes.rb
Rails.application.routes.draw do

  

  devise_for :student_users, :skip => [:sessions], :controllers => { :registrations => 'student_registrations'}

  as :student_user do
    get 'signin' => 'devise/sessions#new', :as => :new_student_user_session
    post 'signin' => 'devise/sessions#create', :as => :student_user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_student_user_session
  end

  # get 'studentportal/index'

  # get 'studentportal/show'

  # devise_for :admin_users
  devise_for :admin_users, :controllers => { :registrations => 'registrations'}, :skip => [:sessions]

  as :admin_user do
    get 'adminsignin' => 'devise/sessions#new', :as => :new_admin_user_session
    post 'adminsignin' => 'devise/sessions#create', :as => :admin_user_session
    delete 'adminsignout' => 'devise/sessions#destroy', :as => :destroy_admin_user_session
  end
  
  get 'contact/new'
  get 'contact/create'

  # get 'onboard', :to => "pages#onboard", :as => "onboard"
  # put "onboard", :to => "pages#onboard_send"

  match 'onboard' =>  "pages#onboard", :via => :get
  match 'onboard' => 'pages#onboard_send', :via => :post

  get 'studentportal', :to => "studentportal#index", :as => "portal"
  get 'coming_soon', :to => "studentportal#done", :as => "coming_soon"
  get 'next_page', :to => "studentportal#next_page", :as => "next_page"
  get 'portal/:permalink', :to => "studentportal#show"

  # resources :lessons
  # resources :sections
  #get 'pages/dashboard'
  

  match 'enroll' =>  "pages#enroll", :via => :get, as: "enroll"
  match 'enroll' => 'pages#create', :via => :post
  match 'homee' =>  "pages#home", :via => :get, as: "homee"


  match ":controller(/:action(/:id))", :via => [:get, :post]
  

  
  root "pages#index"

  mount Ckeditor::Engine => '/ckeditor'
  

  #admin Routes
  get 'pages/dashboard'

  get 'admin/content', to: "admmin#content", as: "admin"

  post 'admin/section_sort', to: "admin#section_sort", as: "sort_sections"
  post 'admin/lesson_sort', to: "admin#lesson_sort", as: "sort_lessons"

  get 'admin/settings'
  get 'admin/section_show/:id', to: "admin#section_show", as: "showsection"
  get 'admin/section_edit/:id', to: "admin#section_edit", as: "editsection"
  delete "admin/section_destroy/:id", to: "admin#section_destroy", as: "destroysection"
  delete "admin/lesson_destroy/:id", to: "admin#lesson_destroy", as: "destroylesson"


  
end

coursify/app/views/pages/_launch_pricing.html.erb
 <div data-alert style="margin:0;  background-color: #89c683;   border:none; border-bottom: 2px solid black;" class="alert-box">
                <div class="pre" >
                

  <p> <strong>Launch Pricing: </strong>The price starts at $1 and increases by $1 (with every sale) until it reaches $<%= final_course_price %></p>
 

</div>
                <a href="#" class="close border-white"  >&times;</a>
              </div>

coursify/app/views/pages/enroll.html.erb
<div class="hdr2" ></div>

    <header>
      <nav>

        <div class="logo" >
          <div class="logo-p2" ><a href="/" >Coursify</a></div>
        </div>

        <ul>
        

          <div class="last" >
          <li><a href="/signin"  >Sign in</a></li>

              

          </div>
        </ul>

      </nav>
    </header>

<div class="top-section-inner" >
<div class="content padtop" >
    <div class="row" >
          <div class="medium-12 columns" > 
          <p class="register-text"  >Create your account</p>
          <p class="rtsub" >And get started in <strong>30 seconds</strong> for only <strong>$<%= current_price %></strong></p>
          </div></div>

          <div class="row" >
            <div class="medium-7 small-12 columns" > 
               
               <div class="panel radius" >


                 <div class="row">
               


          <div><%= devise_error_messages_stripe(@studentuser)  %></div>

            <div><% if flash[:stripe]%>
<% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
          <% end %> </div>
            <div class="small-12 large-12 columns">

            
            <%= form_for( @message, :url => {:action => 'enroll'}) do |form| %>


 <div class="formbody" >

                  <div>
                  <%= form.label :name, 'Full Name:' %>
                  <%= form.text_field :name, :placeholder => "Enter your full name" %>
                  </div>

                  <div>
                  <%= form.label :email, 'Email Address:' %>
                  <%= form.text_field :email, :placeholder => "Enter your email address" %>
                  </div>  

                  <div class="field">
                   
                  <label>Password (8 characters minimum)</label>
                  <%= form.password_field :password, autocomplete: "off" %>
                </div>

           


                  <div>
                  <%= form.hidden_field :subject, value: "OneDayRails Enroll" %>
                  </div>

                         
 </div>

    


    <script src="https://checkout.stripe.com/checkout.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js"></script>


    <button id="customButton" class="button expand success large radius" style="background-color:rgb(216, 38, 46);" >GET STARTED</button>

  <script>
    $('#customButton').click(function(){
      var token = function(res){
        var $input = $('<input type=hidden name=stripeToken />').val(res.id);
        $('form').append($input).submit();
      };

      StripeCheckout.open({
        key:         '<%= Rails.configuration.stripe[:publishable_key] %>',
        amount:      <%= current_price_stripe %>,
        currency:    'usd',
        image:       '/yourlogo.png',
        name:        'Your Course Name',
        description: 'Enroll Today for Only $<%= current_price %>',
        panelLabel:  'GET STARTED',
        token:       token
      });

      return false;
    });
  </script>


    <% end %>
           
  
           
          
              
            </div>
            
          </div>

               </div>
               
            
               
            </div>

            <div class="medium-5 show-for-medium-up columns" > 

          

            <div class="main-img" > <%= image_tag("bg4.jpg") %></div>
            
            
            



            <p>"<strong>Summarise</strong> the main benefit the user will recieve, in one simple sentence and put that here.</p> </div>
          </div>
          

      
    </div>
 </div>





<div class="foot" style="border-top: none;" >

      <%= render(:partial => '/application/footer_partial') %>

     
      
    </div>

</div> 

coursify/app/views/pages/index.html.erb
<% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 

      

      <% if !max_price_reached?  %>
        <%= render "launch_pricing" %>
            <% end %>

      

<div class="hdr2"></div>
<div class="page-body" >
  <div class="header top-section" >
    <div class="top-section-d" style="min-height: 300px; padding-bottom: 120px;" >
    <div class="navigation-bar" >
      <div class="logo" >
          <div class="logo-p" ><p>Coursify</p></div>
        </div>

      <div class="main-nav" >
      <ul>      
              <div class="last" >
                <li><a href="/signin"   >Sign in</a></li>
              </div>
          </ul> 
      </div>      
    </div>

    <div class="course-intro" >
      <h1 class="title" >Your Headline Goes Here...</h1>

      <p class="subtitle" >A quick and easy way to sell your online course and make your students happy...</p>


      <p class="cta" >
     <a href="/enroll" class="alert button small  round" ><i class="fontawesome-shopping-cart" > </i> Enroll in Course for ($<%= current_price %>) </a>
      </p>
      
    </div>      
    </div>
  </div>
  <div class="body" >
    <div class="course-description row" >

      <div class="medium-2 columns hide-for-small-down" >
        <span style="text-align: center;" class="display-block" ><%= image_tag("facebook.png", size: "40x40", alt: "facebook icon")%></span>
        <span style="text-align: center;" class="display-block" ><%= image_tag("twitter.png", size: "40x40", alt: "twitter icon")%></span>
        <span style="text-align: center;" class="display-block" ><%= image_tag("linkedin.png", size: "40x40", alt: "linkedin icon")%></span>
        <span style="text-align: center;" class="display-block" ><a href="#" rel="publisher"><%= image_tag("google-plus.png", size: "40x40", alt: "google-plus icon")%></a></span>
      </div>


      <div class="medium-8 columns" >
        <p><strong>This is where you add your course description.</strong></p>

        <p>Dummy text means you won't see the inevitable variations that show up once real information is entered.</p>

        <p>You'll spend 4 hours going through the videos and another 91 minutes completing the exercises... If you get stuck at anytime, we'll be available to help you out.</p>

        <p>Sure, it's easier to just run down the forms and fill the fields with garbage ("asdsadklja" "123usadfjasld" "snaxn2q9e7") in order to plow through them quickly. But that's not real. That's not what your customers are going to do.</p>

        <p>Join our course today, so you can finally get all the benefits we are promising on this page.</p>

        <p><strong>Prerequisite:</strong></p>

        <p>If you have any prerequesites, you can add them here to let the student know what they need to know before signing up to your courses </p>

        <p><strong>Topics Covered:</strong></p>

        <ul>
          <li>Here, you just need to</li>         
          <li>give a quick summary</li>
          <li>of the content that you'll be selling </li>
          <li>the main benefits</li>
          <li>and how what you are teaching</li>
          <li>will help them achieve their goals</li>
         
        
        </ul>

        <p><strong>Why take this course?</strong></p>

        <p>what is the main reason for the user to take your course? Where are they on their journey towards their goals? Identify with them and explain how your course will help them reach their destination faster.</p>

        <p>You can put your final call to action here. Summarise the main benefits of the course and  demand action at this point. </p>
        <a href="/enroll" class="alert expand button large  radius"><i class="fontawesome-shopping-cart"> </i> Enroll in Course for ($<%= current_price %>) </a>
      </div>
      <div class="medium-2 columns" ></div>
      
    </div>

    <div class="course-instructor " >
        
        <div class="row" >
          <div class="course-instructor-center" >
            <div class="medium-3 columns" ><h2 class="course-instructor-center-heading" ></div>
            <div class="medium-9 columns" ><h2 class="course-instructor-center-heading" >Your Instructor</h2></div>
            <div class="medium-3 columns" style="" >
              <span style="text-align: center;" class="display-block instructor-image" ><%= image_tag("teacher.jpg", alt: "Instructor Picture")%></span>
              <h5 style="font-family: 'Lato', Arial,sans-serif;" class="text-center" >Your Name Here</h5>
              
            </div>

            <div class="medium-9 columns" >
              <p>What makes you qualified to teach this course? Tell the short story of how you learnt the material you are teaching, in this section. More Instructors? Add them below.</p>

              <p>Oh, this is another paragraph to add more text.</p>

              <p>And a third paragraph. Use it wisely.</p>
              
            </div>
          </div>
          
        </div>
    </div>

    <div class="course-curriculum row" >
      
      <div class="medium-8 small-centered columns" >
        <h2 class="course-curriculum-heading" >Course Curriculum</h2>

        
        <ul class="curriculum-ul">
        <% @sections.each do |section|  %>
          <li class="curriculum-section-heading" > <%= section.name %></li>

          <% section.lessons.visible.sorted.each do |lesson| %>
            <%= link_to :controller => 'studentportal', :action => 'show', :permalink => lesson.permalink do %>
                <li class="curriculum-section-item" > 
                <span class="float-left" id=""  ><%= lesson.name %> </span>





                <div class="float-right"  ><span  style=" margin:0; padding-top:0; padding-bottom:0; height: 30px; line-height: 30px;"  class="button radius tiny">Start</span></div>
                <div  class="clear" ></div>
                
                </li>
            <% end %>
          <% end %>
        <% end %>
          
        </ul>
        
      </div>        
    </div>

    <div class="course-faq" >
      <div class="row" >
        <div class="course-faq-center" >
          <div class="medium-12 columns" >
            <h3 class="course-faq-center-heading" >Frequently Asked Questions</h3>

             

               

                <div class="course-faq-question">
                <p>What questions do people ask before they buy?</p>
              </div>
              <div class="course-faq-answer" >
                <p>Make sure you include them all and answer them  succinctly in this FAQ's section. Example below.</p>
              </div>

               <div class="course-faq-question">
                <p>How much prerequisite knowledge do I need to have?</p>
              </div>
              <div class="course-faq-answer" >
                <p>With a basic understanding of HTML and CSS, you'll be able to follow this course comfortably. A basic understanding of the Ruby programming language will also be helpful, but it's definitely not required.</p>
              </div>

               <div class="course-faq-question">
                <p>How much prerequisite knowledge do I need to have?</p>
              </div>
              <div class="course-faq-answer" >
                <p>With a basic understanding of HTML and CSS, you'll be able to follow this course comfortably. A basic understanding of the Ruby programming language will also be helpful, but it's definitely not required.</p>
              </div>

               

          </div>

        </div>        
      </div>
      
    </div>
    
    <div class="course-final-cta row" >

      <div class="medium-8 medium-centered columns"  >
        <h2 class="text-center" >Get Started Today!</h2>
        <p class="cta" >
        <a href="" class="button alert small round" >Enroll in Course for ($<%= current_price %>)</a> 
        </p>
      </div>
      
    </div>
  </div>



<div class="foot" style="border-top: none; background-color: #ecf0f1; padding-top: 80px; margin-top: 30px;" >

     <%= render(:partial => '/application/footer_partial') %>
      
    </div>

</div> 

coursify/app/views/pages/onboard.html.erb
<div class="hdr2" ></div>

    <header>
      <nav>

        <div class="logo" >
          <div class="logo-p2" ><a href="/" >One Day Rails</a></div>
        </div>

        <ul>
        
          <% if student_user_signed_in?%>
          <div class="last" >
          <li><%= link_to "Welcome, #{current_student_user.name}.", edit_student_user_registration_path,  {:style=>'text-transform: capitalize;',} %></li>

          <li> <%= link_to "Sign Out", destroy_student_user_session_path, :class => "button radius small success" , method: :delete %> </li>

              

          </div>

          <% else %>
          <div class="last" >
          <li><a href="#" data-reveal-id="wait" >Sign in</a></li>
          </div>
          <% end %>
        </ul>

      </nav>
    </header>

<div class="top-section-inner" >
<div class="content padtop" >
    <div class="row" >
          <div class="medium-12 columns" > 
          <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
          <p class="register-text"  >Welcome to <strong>Course Name Here!</strong></p>
          <p class="rtsub" >Please answer the 2 questions below, so we can help you get started.</p>
          </div></div>

          <div class="row" >
            <div class="medium-12 small-12 columns" > 
               
               <div class="panel radius" >


                 <div class="row">
                <div class="small-3 large-3 columns">
                </div>
          
            <div class="small-6 large-6 columns">

            
            <%= form_for( @message, :url => {:action => 'onboard'}) do |form| %>


           <div class="formbody" >

               
                  <% if student_user_signed_in?%>
                  <div>
                    <%= form.hidden_field :name, value: "#{current_student_user.name}" %>
                  </div>

                   <div>
                     <%= form.hidden_field :email, value: "#{current_student_user.email}" %>
                   </div>  

                   <% end %>

                  <div>                  
                  <%= form.label :questionone, 'Type the First Question Here' %>
                  <%= form.text_area :questionone, :placeholder => "You can also add a placeholder here" %>
                  </div> 

                  <div>                  
                  <%= form.label :questiontwo, 'Type the Second Question Here' %>
                  <%= form.text_field :questiontwo, :placeholder => "You can also add a placeholder here" %>
                  </div> 
                  
                  

                  
                  


                  <div>
                  <%= form.hidden_field :subject, value: "Add a subject here" %>
                  </div>

                         
            </div>

    <%= form.submit "Continue", :style => 'background-color:rgb(216, 38, 46);' , :class => "button expand success large radius" %>


    <% end %>
           
  
           
          
              
            </div>

            <div class="small-3 large-3 columns">
                </div>
            
          </div>

               </div>
               
            
               
            </div>

            
          </div>
          

      
    </div>
 </div>




<div class="foot" style="border-top: none; padding-top: 30px; margin-top: 30px;" >
    <%= render(:partial => '/application/footer_partial') %>
      
  </div>