coursify/config/routes.rb
Rails.application.routes.draw do

  

  devise_for :student_users, :skip => [:sessions], :controllers => { :registrations => 'student_registrations'}

  as :student_user do
    get 'signin' => 'devise/sessions#new', :as => :new_student_user_session
    post 'signin' => 'devise/sessions#create', :as => :student_user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_student_user_session
  end

  # get 'studentportal/index'

  # get 'studentportal/show'

  # devise_for :admin_users
  devise_for :admin_users, :controllers => { :registrations => 'registrations'}, :skip => [:sessions]

  as :admin_user do
    get 'adminsignin' => 'devise/sessions#new', :as => :new_admin_user_session
    post 'adminsignin' => 'devise/sessions#create', :as => :admin_user_session
    delete 'adminsignout' => 'devise/sessions#destroy', :as => :destroy_admin_user_session
  end
  
  get 'contact/new'
  get 'contact/create'

  # get 'onboard', :to => "pages#onboard", :as => "onboard"
  # put "onboard", :to => "pages#onboard_send"

  match 'onboard' =>  "pages#onboard", :via => :get
  match 'onboard' => 'pages#onboard_send', :via => :post

  get 'studentportal', :to => "studentportal#index", :as => "portal"
  get 'coming_soon', :to => "studentportal#done", :as => "coming_soon"
  get 'next_page', :to => "studentportal#next_page", :as => "next_page"
  get 'portal/:permalink', :to => "studentportal#show"

  # resources :lessons
  # resources :sections
  #get 'pages/dashboard'
  

  match 'enroll' =>  "pages#enroll", :via => :get, as: "enroll"
  match 'enroll' => 'pages#create', :via => :post
  match 'homee' =>  "pages#home", :via => :get, as: "homee"


  match ":controller(/:action(/:id))", :via => [:get, :post]
  

  
  root "pages#index"

  mount Ckeditor::Engine => '/ckeditor'
  

  #admin Routes
  get 'pages/dashboard'

  get 'admin/content', to: "admmin#content", as: "admin"

  post 'admin/section_sort', to: "admin#section_sort", as: "sort_sections"
  post 'admin/lesson_sort', to: "admin#lesson_sort", as: "sort_lessons"

  get 'admin/settings'
  get 'admin/section_show/:id', to: "admin#section_show", as: "showsection"
  get 'admin/section_edit/:id', to: "admin#section_edit", as: "editsection"
  delete "admin/section_destroy/:id", to: "admin#section_destroy", as: "destroysection"
  delete "admin/lesson_destroy/:id", to: "admin#lesson_destroy", as: "destroylesson"


  
end

coursify/app/controllers/studentportal_controller.rb
class StudentportalController < ApplicationController
  layout "portal"
  before_action :authenticate_student_user!
  before_action :setup_navigation
  before_action :find_section, except: [:index, :done, :next_page]
  
  def index
    first_section = Section.where(:position => 1).first
    @first_lesson =  Lesson.where(:section_id => first_section.id, :position => 1).first     
    @current_student_user = current_student_user
    if current_student_user.last_viewed_lecture
      @last_lesson = Lesson.where(:permalink => current_student_user.last_viewed_lecture, :visible => true).first
    end
  end

  def done
  end

  def show
    @lesson = Lesson.where(:permalink => params[:permalink], :visible => true).first

    
    if @lesson.nil?
      redirect_to(:action => "index")
    else    
      
      current_student_user.update_attribute(:last_viewed_lecture, @lesson.permalink)
      @current_student_user = current_student_user

      @permalink = params[:permalink]      
      @sections_all = Section.count
      @current_section = current_section
      @current_section_size = size_of_section(@current_section)
      @current_lesson_position = lesson_position(@lesson)
      
      if @current_lesson_position <= (@current_section_size - 1)
        @next_lesson_position = @current_lesson_position + 1
        @next_lesson_object = Lesson.where(:section_id => @current_section.id, :position => @next_lesson_position).first      
      elsif @current_lesson_position == @current_section_size
        if @current_section.position == @sections_all
          @next_lesson_object = Lesson.new(:name => "Conclusion...")
          return false
        end    
        @next_section = next_section
        
        while @next_section.lessons.size < 1
          if @next_section.position == @sections_all
            @next_lesson_object = Lesson.new(:name => "Conclusion...")
            return false
            break
          else
            cs = @next_section.position
            if cs <= (@sections_all - 1)
              nxt_section_position = cs + 1 
              nxt_section = Section.where(:position => nxt_section_position).first
              @next_section = nxt_section
            end
          end
        end        

        @next_lesson_object = Lesson.where(:section_id => @next_section.id, :position => 1).first           
      end
    end
  end

  def next_page
    @permalink = params[:permalink]
    @lesson = Lesson.where(:permalink => params[:permalink], :visible => true).first      
    @sections_all = Section.all.size
    @current_section = current_section
    @current_section_size = size_of_section(@current_section)
    @current_lesson_position = lesson_position(@lesson)
    
    if @current_lesson_position <= (@current_section_size - 1)
      @next_lesson_position = @current_lesson_position + 1
      @next_lesson_object = Lesson.where(:section_id => @current_section.id, :position => @next_lesson_position).first
      redirect_to "/portal/#{@next_lesson_object.permalink}"       
    elsif @current_lesson_position == @current_section_size
      if @current_section.position == @sections_all
        redirect_to coming_soon_path
        return false
      end    
      @next_section = next_section
      
      while @next_section.lessons.size < 1
        if @next_section.position == @sections_all
          redirect_to coming_soon_path
          return false
          break
        else
          cs = @next_section.position
          if cs <= (@sections_all - 1)
            nxt_section_position = cs + 1 
            nxt_section = Section.where(:position => nxt_section_position).first
            @next_section = nxt_section
          end
        end
      end        

      @next_lesson_object = Lesson.where(:section_id => @next_section.id, :position => 1).first     
      redirect_to "/portal/#{@next_lesson_object.permalink}"
    end
  end

  private

  def setup_navigation
    @sections  = Section.visible.sorted
  end

  def find_section
    lesson = Lesson.where(:permalink => params[:permalink], :visible => true).first
    # @section_id = @lesson.section_id
    @section = Section.find(lesson.section_id)
  end

  def next_section
    cs = @current_section.position
    if cs <= (@sections_all - 1)
      nxt_section_position = cs + 1 
      nxt_section = Section.where(:position => nxt_section_position).first
      return nxt_section
    end       
  end

  def current_section
    @lesson = Lesson.where(:permalink => params[:permalink], :visible => true).first
      @section_id = @lesson.section_id
      return Section.find(@section_id)    
  end

  def size_of_section(section)
    section_size = section.lessons.size
    return section_size
  end

  def lesson_position(lesson)
    lp = lesson.position
    return lp
  end



  # def next_lesson_position(lesson)
  #   current_lesson_position = lesson_position(lesson)
  #   section_size = size_of_section(what_section)

  #   if section_size >= (current_lesson_position + 1)
  #     n_l_p = current_lesson_position + 1
  #     return n_l_p
  #   else
  #     find_next_section(what_section)
  #   end

  #   lpp = lpp +1
  #   return lpp
  # end
end

coursify/app/helpers/studentportal_helper.rb
module StudentportalHelper
	
	

end

coursify/app/views/studentportal/done.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1  class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  

      

           <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_student_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
            <a href="/student_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
            

      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div  class="portal-nav medium-3 columns show-for-medium-up" id="toggle-menu"  >
        <ul class="curriculum-ul">
        <span id='this'></span>
        <% @sections.each do |section|  %>
          <li class="curriculum-section-heading" > <%= section.name %></li>

          <% section.lessons.visible.sorted.each do |lesson| %>
            
            
            <%= link_to :controller => 'studentportal', :action => 'show', :permalink => lesson.permalink do %>
                <li class="curriculum-section-item <%= current_page?("/portal/#{lesson.permalink}")? "thisbg" : " " %>"  > 
                
                <%= current_page?("/portal/#{lesson.permalink}")? "<span id='this'></span>".html_safe : " " %>

                <span class="float-left" id="<%= current_page?("/portal/#{lesson.permalink}")? "" : " " %>"  ><%= lesson.name %>   </span>


                <!-- <div class="float-right"  ><span  style=" margin:0; padding-top:0; padding-bottom:0; height: 30px; line-height: 30px;"  class="button radius tiny">Start</span></div> -->
                <div  class="clear" ></div>
                
                </li>
            <% end %>            
          <% end %>
          
        <% end %>
          
        </ul>
        
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >
       <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
         <h3 style="text-transform: none;" class="text-left" >Congratulations! You have finished Course Name.</h3>

    <hr>

    <p>Add some farewell information here, and you can even pre-sell a new course.</p>




        
         

          
       </div>

    </div>
    </div>
</div>

coursify/app/views/studentportal/index.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_student_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
            <a href="/student_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >
       <ul class="curriculum-ul">
       <span id='this'></span>
        <% @sections.each do |section|  %>
          <li class="curriculum-section-heading" > <%= section.name %></li>

          <% section.lessons.visible.sorted.each do |lesson| %>
            
            
            <%= link_to :controller => 'studentportal', :action => 'show', :permalink => lesson.permalink do %>
                <li class="curriculum-section-item <%= current_page?("/portal/#{lesson.permalink}")? "thisbg" : " " %>"  > 
                
                <%= current_page?("/portal/#{lesson.permalink}")? "<span id='this'></span>".html_safe : " " %>

                <span class="float-left"   ><%= lesson.name %>   </span>


                <div  class="clear" ></div>
                
                </li>
            <% end %>            
          <% end %>
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >
       <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
          <h3 class="text-left"  >Welcome to One Day Rails.</h3>
        
            <hr>
          <div class="portal-home-next-lecture-block" >
            <% if current_student_user.last_viewed_lecture == nil %>
            <div class="next-lecture " >
              
              <%= link_to("Start Your First Lesson", "/portal/#{@first_lesson.permalink}" , class: "button round") %>
              <p class="display-inline" ><%= "#{@first_lesson.name}" %>  </p>
            </div>
            <% else %>
            <div class="next-lecture " >
              
              <%= link_to("Continue Last Lesson", "/portal/#{@current_student_user.last_viewed_lecture}" , class: "button round") %>
              <p class="display-inline" ><%= "#{@last_lesson.name}" %>  </p>
            </div>
            <% end %>

          </div>

          <div style="padding-bottom: 460px;" class="flex-video" >
            <iframe src="//fast.wistia.net/embed/iframe/ixvkw3bm6g?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe><script src="//fast.wistia.net/assets/external/E-v1.js"></script>
          </div>

        
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/studentportal/show.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1  class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  

            
        <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_student_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
            <a href="/student_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div  class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >
             <ul class="curriculum-ul">
        <% @sections.each do |section|  %>
          <li class="curriculum-section-heading" > <%= section.name %></li>

          <% section.lessons.visible.sorted.each do |lesson| %>
            
            
            <%= link_to :controller => 'studentportal', :action => 'show', :permalink => lesson.permalink do %>
                <li class="curriculum-section-item <%= current_page?("/portal/#{lesson.permalink}")? "thisbg" : " " %>"  > 
                
                <%= current_page?("/portal/#{lesson.permalink}")? "<span id='this'></span>".html_safe : " " %>

                <span class="float-left"   ><%= lesson.name %>   </span>


                <!-- <div class="float-right"  ><span  style=" margin:0; padding-top:0; padding-bottom:0; height: 30px; line-height: 30px;"  class="button radius tiny">Start</span></div> -->
                <div  class="clear" ></div>
                
                </li>
            <% end %>            
          <% end %>
          
        <% end %>
          
        </ul>
        
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >

       <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 

              <h3 class="text-left" >  <%=  @lesson.name %> <br><small>From <%=  @section.name %></small></h3>
            <hr />

           <%= raw(@lesson.body) %>



            <div class="next-lecture" >
              <%= link_to("Next Lesson", next_page_path(:permalink => @lesson.permalink, :section_id => @lesson.section_id), class: "button round ") %>

              <p class="display-inline" ><%= "#{@next_lesson_object.name}" %> </p>
            </div>
             

               <%= render(:partial => '/application/disqus_partial') %>
       </div>

    </div>
    </div>


</div>


   